# a build.yml to build Habitus cross-platform using Habitus
build:
  version: 2016-03-14
  steps:
    tester:
      name: tester
      dockerfile: Dockerfile.tester
      command: go test
    crosscompile:
      name: crosscompile
      depends_on:
        - tester
      dockerfile: Dockerfile.crosscompile
      artifacts:
        # copy all the artifacts from the compiled folder
        - /usr/local/go/src/github.com/cloud66-oss/habitus/compiled:.