build:
  version: 2016-03-14
  steps:
    builder:
      name: builder
      dockerfile: Dockerfile.builder
      artifacts:
        - /usr/local/go/src/github.com/cloud66/habitus/habitus:./artifacts/habitus
    tester:
      name: tester
      depends_on:
        - builder
      dockerfile: Dockerfile.tester
      command: go test
    crosscompile:
      name: crosscompile
      depends_on:
        - tester
      dockerfile: Dockerfile.crosscompile
      artifacts:
        - /usr/local/go/src/github.com/cloud66/habitus/compiled/habitus_darwin_386:./artifacts/compiled
        - /usr/local/go/src/github.com/cloud66/habitus/compiled/habitus_darwin_amd64:./artifacts/compiled
        - /usr/local/go/src/github.com/cloud66/habitus/compiled/habitus_windows_386.exe:./artifacts/compiled
        - /usr/local/go/src/github.com/cloud66/habitus/compiled/habitus_windows_amd64.exe:./artifacts/compiled
        - /usr/local/go/src/github.com/cloud66/habitus/compiled/habitus_linux_386:./artifacts/compiled
        - /usr/local/go/src/github.com/cloud66/habitus/compiled/habitus_linux_amd64:./artifacts/compiled
